### ISSUE TITLE
After validated a submitted script, you have to reject all older submitted script versions

### ISSUE THREAD

**Issue by legluondunet** [lutris/lutris-dashboard#30]
Hello,
when I validate a submitted script modification, I have to reject all older submitted script modifications.
Sometimes there are more than 20 modifications to reject, it takes a lot of time and it is useless as we have already validated a script.
What about to automatically reject all all older submitted script versions when a modo validated one of them?

**Comment by legluondunet** [comment]
for example, I would like to validate one of the World of Tank script:

![Capture d’écran de 2020-12-04 12-00-07](https://user-images.githubusercontent.com/325405/101237813-033d8300-36dc-11eb-9cb8-1eeee42422fc.png)

as you can see on the picture, I have still 65 submitted modifications to reject after validated one of them to hide "review" mention.

**Comment by strycore** [comment]
I don't want to implement this.
There might be 2 different submissions for 2 different things. The only reason this was ever wanted is because the moderation queue was clogged up and the dashboard goes from most recent to oldest, so the most recent gets approved first.
The moderation queue is no longer clogged up and I have added at the top when the installer was last updated. So it the installer was updated more recently than the submission then it's a red flag that it may need to be rejected, but not necessarily.
Also a lot of stuff gets automatically deleted now. If a draft were to be similar to the currently published version, it is now deleted within the hour.
